# Generated by Django 4.2.7 on 2024-01-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='is_active',
        ),
    ]
